/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "greeter.h"
#include <cassert>

int main() {
    assert(say_hello("World").compare("Bonjour, World! I'm using Discord GameSDK version 3!") == 0);
    return 0;
}
